### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by fahimsakri** [segmentio/analytics-android#539]
Getting this error after upgrading gms to 11.2.2 version and segment libs to latest version

  ```
  java.lang.NoSuchMethodError: No static method zzw(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/co.go.fynd.debug-2/base.apk:classes2.dex)
                                                                      at com.google.android.gms.internal.zzsc.zzan(Unknown Source)
                                                                      at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
                                                                      at com.segment.analytics.android.integrations.google.analytics.GoogleAnalyticsIntegration$1.create(GoogleAnalyticsIntegration.java:60)
                                                                      at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1447)
                                                                      at com.segment.analytics.Analytics$2$1.run(Analytics.java:275)
                                                                      at android.os.Handler.handleCallback(Handler.java:742)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by f2prateek** [comment]
Duplicate of https://github.com/segment-integrations/analytics-android-integration-google-analytics/issues/12
